# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [5]:
import numpy as np
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[7,8,9],[10,11,12]])
C=np.array([[13,14,15],[16,17,18]])

sum_of_BC=B+C
A_times_sum=np.dot(A,sum_of_BC)
A_times_B=np.dot(A,B)
A_times_C=np.dot(A,C)
sum_of_products=A_times_B+A_times_C

print(A_times_sum)
print('\n is equal to \n')
print(sum_of_products)

[[ 72  78  84]
 [164 178 192]
 [256 278 300]]

 is equal to 

[[ 72  78  84]
 [164 178 192]
 [256 278 300]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [6]:
C=([[13,14],[15,16],[17,18]])
B_times_C=np.dot(B,C)
A_times_product=np.dot(A,B_times_C)

A_times_B=np.dot(A,B)
product_times_C=np.dot(A_times_B,C)

print(A_times_product)
print('\n is equal to \n')
print(product_times_C)

[[1362 1452]
 [3088 3292]
 [4814 5132]]

 is equal to 

[[1362 1452]
 [3088 3292]
 [4814 5132]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [7]:
# Your code here 
A_times_B=np.dot(A,B)
B_times_A=np.dot(B,A)

print(A_times_B)
print('\n is not equal to \n')
print(B_times_A)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

 is not equal to 

[[ 76 100]
 [103 136]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [8]:
x=np.array([1,2,3])
y=np.array([4,5,6])

x_transpose=x.T
y_transpose=y.T

x_transpose_y=x_transpose*y
y_transpose_x=y_transpose*x

print(x_transpose_y)
print('\nis equal to\n')
print(y_transpose_x)

[ 4 10 18]

is equal to

[ 4 10 18]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [9]:
product=np.dot(A,B)
product_transposed=product.T

B_transpose=B.T
A_transpose=A.T
transpose_product=np.dot(B_transpose,A_transpose)

print(product_transposed)
print('\n is equal to \n')
print(transpose_product)

[[ 27  61  95]
 [ 30  68 106]
 [ 33  75 117]]

 is equal to 

[[ 27  61  95]
 [ 30  68 106]
 [ 33  75 117]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 